config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#show_about', as: :pages_about
  get 'contact', to: 'pages#show_contact', as: :pages_contact

  get 'about/edit', to: 'pages#edit_about', as: :edit_about
  patch 'about/update', to: 'pages#update_about', as: :update_about

  get 'contact/edit', to: 'pages#edit_contact', as: :edit_contact
  patch 'contact/update', to: 'pages#update_contact', as: :update_contact

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }
  
  root to: "home#index"

  resources :categories, only: [:show]

  resources :products

  resources :orders, only: [:create]

  get '/search', to: 'products#search'

  post '/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_quantity/:id', to: 'cart#update_quantity', as: 'update_quantity'
  get '/remove_item/:id', to: 'cart#remove_item', as: 'remove_item'
  get '/cart', to: 'cart#show_cart', as: 'cart'

  get '/confirm_order', to: 'checkout#confirm_order', as: 'confirm_order_checkout'
  get '/checkout', to: 'checkout#checkout', as: 'checkout_checkout'
  get '/order_confirmed', to: 'checkout#order_confirmed', as: 'order_confirmed'
  patch '/update_address', to: 'checkout#update_address', as: 'address_checkout'

  get '/profile/edit', to: 'profile#edit', as: 'edit_profile'
  patch '/profile/update', to: 'profile#update', as: 'update_profile'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_to_cart
    product_id = params[:id]
    product = Product.find(product_id)

    session[:cart] ||= {}
    session[:cart][product_id] ||= 0
    session[:cart][product_id] += 1
    
    redirect_to root_path, notice: 'Product added to cart'
  end

  def update_quantity
    product_id = params[:id]
    quantity = params[:quantity].to_i
    session[:cart][product_id] = quantity if session[:cart].key?(product_id)
    redirect_to cart_path, notice: 'Quantity updated'
  end

  def remove_item
    product_id = params[:id]
    session[:cart].delete(product_id) if session[:cart].key?(product_id)
    redirect_to cart_path, notice: 'Item removed from cart'
  end

  def show_cart
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/show_cart.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-4">Your Cart</h1>

  <% if session[:cart].present? %>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <% session[:cart].each do |product_id, quantity| %>
        <% product = Product.find(product_id) %>
        <div class="border rounded p-4">
          <p class="text-lg mb-2"><%= product.name %> - Quantity:</p>
          <%= form_tag update_quantity_path(id: product.id), method: :patch, class: "flex items-center" do %>
            <%= number_field_tag :quantity, quantity, in: 1..10, class: "border border-gray-300 px-2 py-1 rounded ml-2" %>
            <%= submit_tag 'Update', class: "bg-blue-500 text-white px-3 py-1 rounded ml-2 hover:bg-blue-600 focus:outline-none" %>
          <% end %>
          <%= link_to 'Remove', remove_item_path(product), method: :post, data: { confirm: 'Are you sure?' }, class: "text-red-500 ml-2" %>
        </div>
      <% end %>
    </div>
    <div class="mt-4 sm:grid sm:justify-end">
      <%= link_to 'Checkout', checkout_checkout_path, class: "bg-green-500 text-white font-bold py-2 px-4 rounded hover:bg-green-600 focus:outline-none" %>
    </div>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
</div>