config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#show_about', as: :pages_about
  get 'contact', to: 'pages#show_contact', as: :pages_contact

  get 'about/edit', to: 'pages#edit_about', as: :edit_about
  patch 'about/update', to: 'pages#update_about', as: :update_about

  get 'contact/edit', to: 'pages#edit_contact', as: :edit_contact
  patch 'contact/update', to: 'pages#update_contact', as: :update_contact

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }
  
  root to: "home#index"

  resources :categories, only: [:show]

  resources :products

  resources :orders, only: [:create]

  get '/search', to: 'products#search'

  post '/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_quantity/:id', to: 'cart#update_quantity', as: 'update_quantity'
  get '/remove_item/:id', to: 'cart#remove_item', as: 'remove_item'
  get '/cart', to: 'cart#show_cart', as: 'cart'

  get '/confirm_order', to: 'checkout#confirm_order', as: 'confirm_order_checkout'
  get '/checkout', to: 'checkout#checkout', as: 'checkout_checkout'
  get '/order_confirmed', to: 'checkout#order_confirmed', as: 'order_confirmed'
  patch '/update_address', to: 'checkout#update_address', as: 'address_checkout'

  get '/profile/edit', to: 'profile#edit', as: 'edit_profile'
  patch '/profile/update', to: 'profile#update', as: 'update_profile'
end

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800 text-white py-4">
  <div class="container mx-auto flex justify-between items-center">
    <div class="flex items-center">
      <%= link_to "Home", root_path, class: "mr-4" %>
      <%= link_to 'About', pages_about_path, class: "mr-4" %>
      <%= link_to 'Contact', pages_contact_path %>
    </div>
    <div class="flex items-center relative">
      <%= link_to cart_path, class: "relative mr-4" do %>
        Cart
        <% if session[:cart].present? %>
        <span class="bg-red-500 text-white rounded-full h-4 w-4 flex items-center justify-center absolute -bottom-1 -right-0 transform translate-x-2">
          <%= session[:cart].values.sum %>
        </span>
        <% end %>
      <% end %>
      <%= link_to "Profile[#{current_user.role}]", edit_profile_path, class: "mr-4" %>
      <%= button_to "Log out", destroy_user_session_path, method: 'delete' %>
    </div>
  </div>
</nav>

app/views/shared/_product.html.erb
<% @products.each do |product| %>
    <div class="bg-gray-100 p-6 rounded shadow-md border border-gray-300 relative">
        <div class="flex justify-between items-center mb-4">
            <%= link_to product.name, product_path(product), class: "text-blue-600 hover:underline font-semibold text-lg text-center w-full" %>
        </div>

        <div class="h-24 overflow-hidden mb-2">
            <p class="text-gray-700">
                <%= truncate(product.description, length: 100, separator: ' ') %>
            </p>
        </div>

        <% if current_user.regular? %>
            <div class="text-center">
                <span class="text-gray-600 font-semibold block mb-1"><%= number_to_currency(product.price) %></span>
                <%= button_to 'Add to Cart', add_to_cart_path(product), method: :post, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded focus:outline-none mt-2" %>
            </div>
        <% end %>

        <% if current_user.admin? %>
            <div class="flex justify-center space-x-2 mt-2">
                <%= link_to 'Edit', edit_product_path(product), class: "bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded" %>
                <%= form_with(url: product_path(product), method: :delete, data: { confirm: 'Are you sure?' }) do |form| %>
                    <%= form.submit 'Delete', class: "bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded" %>
                <% end %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/shared/_search_bar.html.erb
<%= form_tag(search_path, method: :get, class: "flex items-center mb-4") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search products", class: "border border-gray-300 px-4 py-2 rounded-l-md focus:outline-none flex-1" %>
  <%= select_tag :category, options_from_collection_for_select(Category.all, 'id', 'name'), include_blank: true, class: "border border-l-0 border-gray-300 px-4 py-2 rounded-r-md focus:outline-none" %>
  <%= submit_tag "Search", class: "bg-blue-500 text-white px-4 py-2 rounded-md ml-2 hover:bg-blue-600 focus:outline-none" %>
<% end %>