config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#show_about', as: :pages_about
  get 'contact', to: 'pages#show_contact', as: :pages_contact

  get 'about/edit', to: 'pages#edit_about', as: :edit_about
  patch 'about/update', to: 'pages#update_about', as: :update_about

  get 'contact/edit', to: 'pages#edit_contact', as: :edit_contact
  patch 'contact/update', to: 'pages#update_contact', as: :update_contact

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }
  
  root to: "home#index"

  resources :categories, only: [:show]

  resources :products

  resources :orders, only: [:create]

  get '/search', to: 'products#search'

  post '/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_quantity/:id', to: 'cart#update_quantity', as: 'update_quantity'
  get '/remove_item/:id', to: 'cart#remove_item', as: 'remove_item'
  get '/cart', to: 'cart#show_cart', as: 'cart'

  get '/confirm_order', to: 'checkout#confirm_order', as: 'confirm_order_checkout'
  get '/checkout', to: 'checkout#checkout', as: 'checkout_checkout'
  get '/order_confirmed', to: 'checkout#order_confirmed', as: 'order_confirmed'
  patch '/update_address', to: 'checkout#update_address', as: 'address_checkout'

  get '/profile/edit', to: 'profile#edit', as: 'edit_profile'
  patch '/profile/update', to: 'profile#update', as: 'update_profile'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.all.page(params[:page]).per(20)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullStackTreats</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="bg-gray-100">
  <% if !current_user %>
    <div class="flex justify-end p-4">
      <a href="<%= new_user_registration_path %>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Sign Up</a>
      <a href="<%= new_user_session_path %>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-4">Log In</a>
    </div>
  <% end %>

  <% if current_user %>
    <%= render 'shared/navbar' %>
    <div class="container mx-auto px-4 py-8">
      <h1 class="text-3xl font-bold mb-4 text-center">FullStackTreats</h1>

      <% if current_user.admin? %>
        <p>There are <%= User.count %> users in the system.</p>
      <% end %>

      <div class="flex justify-center mb-4">
        <%= render 'shared/search_bar' %>
      </div>

      <div class="flex flex-wrap justify-between mb-4">
        <% @categories.each do |category| %>
          <a href="<%= category_path(category) %>"
             class="bg-gray-200 hover:bg-gray-300 text-gray-800 font-bold py-2 px-4 rounded mb-2 mr-2">
            <%= category.name %>
          </a>
        <% end %>
      </div>

      <% if current_user.admin? %>
        <a href="<%= new_product_path %>" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Add New Product</a>
      <% end %>

      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">
        <%= render 'shared/product' %>
      </div>

      <div class="flex justify-center mt-4">
        <%= paginate @products, class: 'pagination' %>
      </div>
    </div>
  <% end %>
</body>

</html>