config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#show_about', as: :pages_about
  get 'contact', to: 'pages#show_contact', as: :pages_contact

  get 'about/edit', to: 'pages#edit_about', as: :edit_about
  patch 'about/update', to: 'pages#update_about', as: :update_about

  get 'contact/edit', to: 'pages#edit_contact', as: :edit_contact
  patch 'contact/update', to: 'pages#update_contact', as: :update_contact

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }
  
  root to: "home#index"

  resources :categories, only: [:show]

  resources :products

  resources :orders, only: [:create]

  get '/search', to: 'products#search'

  post '/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  patch '/update_quantity/:id', to: 'cart#update_quantity', as: 'update_quantity'
  get '/remove_item/:id', to: 'cart#remove_item', as: 'remove_item'
  get '/cart', to: 'cart#show_cart', as: 'cart'

  get '/confirm_order', to: 'checkout#confirm_order', as: 'confirm_order_checkout'
  get '/checkout', to: 'checkout#checkout', as: 'checkout_checkout'
  get '/order_confirmed', to: 'checkout#order_confirmed', as: 'order_confirmed'
  patch '/update_address', to: 'checkout#update_address', as: 'address_checkout'

  get '/profile/edit', to: 'profile#edit', as: 'edit_profile'
  patch '/profile/update', to: 'profile#update', as: 'update_profile'
end

app/views/pages/edit_about.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-4">Edit About Page</h1>

  <%= form_tag update_about_path, method: :patch, class: "w-full max-w-lg" do %>
    <%= text_area_tag :about_content, @about_content, class: "border border-gray-300 px-3 py-2 rounded focus:outline-none w-full mb-4" %>
    <%= submit_tag 'Update', class: "bg-blue-500 text-white font-bold py-2 px-4 rounded hover:bg-blue-600 focus:outline-none" %>
  <% end %>
</div>

app/views/pages/edit_contact.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-4">Edit Contact Page</h1>

  <%= form_tag update_contact_path, method: :patch, class: "w-full max-w-lg" do %>
    <%= text_area_tag :contact_content, @contact_content, class: "border border-gray-300 px-3 py-2 rounded focus:outline-none w-full mb-4" %>
    <%= submit_tag 'Update', class: "bg-blue-500 text-white font-bold py-2 px-4 rounded hover:bg-blue-600 focus:outline-none" %>
  <% end %>
</div>

app/views/pages/show_about.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-4">About Page</h1>

  <p class="text-lg"><%= @about_content %></p>

  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_about_path, class: "text-blue-500 hover:underline" %>
  <% end %>
</div>

app/views/pages/show_contact.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-4">Contact Page</h1>

  <p class="text-lg"><%= @contact_content %></p>

  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_contact_path, class: "text-blue-500 hover:underline" %>
  <% end %>
</div>